SONG_LIST = [
    "Roop Tera Mastana",
    "Ude Jab Jab Julfen Teri",
    "Khaike Paan Banaras Wala",
    "Rang Barse Bhige",
    "Kabhi Kabhi Mere Dil Mei",
    "Pyaar Hua Ekraar Hua",
    "Babuji Dheere Chalna",
    "Jhumka Gira Re",
    "Chura Lia Hai Tumne",
    "Chhor Do Aanchal Zamana",
    "Chahe Koi Mujhe Junglee Kahe",
    "Gunguna Rahi Hain Bhavare",
    "Aaiye Meharwa",
    "Do Lafzon Ki Hai",
    "Chalte Chalte Mere Ye Geet",
    "Jhoot Bole Kaiwa Kaatein",
    "Aye Meri Zohrazabin",
    "Tere Mast Mast Do Nain",
    "Hum Tumhe Chahte Hain Aise",
    "Ruk Ja O Jaane Waali",
    "Mere Sapno Ki Rani",
    "Humei Tumse Pyaar Kitna",
    "Aaja Sanam Madhur Chandani Mei",
    "Kajraare Kajraare",
    "Bidi Jalai Le",
    "Mera Juta Hai Japani",
    "Hothon Se Chulo Tum",
    "Pyaar Hua Ekraar Hua",
    "Sajna Hai Mujhe Sajna Ke Liye",
    "Ek Ladki Bheegi Bhaagi Si",
    "Kehta Hai Joker Saara Zamaana",
    "Le Jaayenge Dilwaale Dulhaniya",
    "Lag Jaa Gale Se Ki Phir Ye",
    "Badan Pe Sitaare",
    "Jaa ne Jaan Dhundta Fir Raha",
    "Aye Bhai Jara Dekhke Chalo",
    "Mere Sapno Ki Raani",
    "My Name is Anthony",
    "Dam Dam Diga Diga",
    "Ye Galia Ye Chaubara",
    "Yamma Yamma Hai Khoobsurat",
    "Mere Haathon Mei Nau Nau Chudiyaan",
    "Ramchandra Keh Gye Sia Se",
    "O Saathi Re Tere Bina Bhi Kya Jeena",
    "Aaj Blue Hai Paani Paani",
    "Ek Pyaar Ka Nagma Hai",
    "Koi Jab Tumhara Hridaya Tod De",
    "Balam Pichkaari",
    "Jaha Mai Jaati Hu Wahin Chale",
    "Inn Aankhon Ki Masti Ke",
    "Chandan Saa Badan",
    "Chaand Aahe Bharega",
    "Papa Kehte Hain Bada Naam Karega",
    "Tumko Dekha To Yeh Khayal Aaya",
    "Chaudhvin Ka Chand Ho",
    "Bahon Mei Chali Aao",
    "Ek Do Teen",
    "Haaye Haaye Yeh Majboori",
    "Ye Chand Sa Roshan Chehra",
    "Munni Badnaam Hui",
    "Mai Shayar To Nahi",
    "Haal Kaisa Hai Janaab Ka",
    "Ek Din Bik Jaayega Maati Ke Mol",
    "Bekaraar Krke Hume Yuu Naa Jaayiye",
    "Piyaa Tu Ab To Aajaa",
    "Hum To Tere Aashiq Hai",
    "Husn Haajir Hai Mohabbat Ki",
    "Husn Ke Laakhon Rang",
    "Hum Bewafa Hargiz Na The",
    "Aaja Aaja Mai Hu Pyaar Tera",
    "Chandi Jaisa Rang Hai Tera",
    "Koi Kahe Kehta Rahe",
    "Ye Kaali Kaali Aankhen",
    "Jai Jai Shiv Shankar",
    "Mere Angane Mei Tumhara",
    "Jaane Kyu Log Mohabbat Kiya",
    "Le Chal Le Chal Mere Jeevan Saathi",
    "Dekha Na Haaye Re Socha Na",
    "Ghum Hai Kisi Ke Pyaar Mei",
    "Hai Apna Dil To Awaara",
    "Dil Kya Kare Jab Kisiko",
    "Bachna Aye Hasino",
    "Salaam Ae Ishq Meri Jaan",
    "Leke Pehla Pehla Pyaar",
    "Hum Kaale Hai To Kya Hua",
    "Ke Pag Ghumguroo Baandhe",
    "Ek Mai Aur Ek Tu",
    "Kaanta Laga Haaye Laga",
    "Kuch To Log Kahenge",
    "Chingaari Koi Bhadke"
  ]