SONG_LIST = [
    "Roop Tera Mastana",
    "Ude Jab Jab Julfen Teri",
    "Khaike Paan Banaras",
    "Rang Barse Bhige",
    "Kabhi Kabhi Mere Dil",
    "Pyaar Hua Ikraar Hua",
    "Babuji Dheere Chalo",
    "Jhumka Gira Re",
    "Chura Lia Hai Tumne",
    "Chhor Do Aanchal Zamana",
    "Chahe Koi Mujhe Junglee",
    "Gunguna Rahi Hain",
    "Aaiye Meharwa",
    "Do Lafzon Ki Hai",
    "Chalte Chalte",
    "Jhoot Bole Kaiwa Kaatein",
    "Aye Meri Zohrazabin",
    "Tere Mast Mast Do Nain",
    "Hum tumhe Chahte Hain",
    "Ruk Ja O Jaane Waali",
    "Mere Sapno Ki Rani",
    "Humei Tumse Pyaar Kitna",
    "Aaja Sanam Madhur",
    "Kajraare Kajraare",
    "Bidi Jalai Le",
    "Mera Juta Hai Japani",
    "Hothon Se Chulo Tum",
    "Pyaar Hua Ikraar Hua",
    "Sajna Hai Mujhe Sajna Ke Liye",
    "Ek Ladki Bheegi Bhaagi Si",
    "Kehta Hai Jokar Saara",
    "Le Jaayenge Dilwaale Dulhaniya",
    "Lag Jaa Gale Ki Phir Ye",
    "Badan Pe Sitaare",
    "Jaane ne Jaa Dhundta Fir Raha",
    "Aye Bhai Jara Dekhke Chalo",
    "Mere Sapno Ki Raani",
    "My Name is Anthony",
    "Dam Dam Diga Diga",
    "Ye Galia Ye Chaubara",
    "Yamma Yamma hai Khoobsurat",
    "Mere Haathon Mei Nau Nau Chudiyaan",
    "Ramchandra Keh Gye Sia Se",
    "O Saathi Re Tere Bina Kya Jeena",
    "Aaj Blue Hai Paani Paani",
    "Ek Pyaar Ka Nagma Hai",
    "Koi Jab Tumhara Hridaya Tod",
    "Balam Pichkaari",
    "Jaha Mai Jaati Hu Vaha Chale",
    "Inn Aankhon Ki Masti",
    "Chandan saa Badan",
    "Chaand Aahe Bharega",
    "Papa Kehte Hain Bada Naam Karega",
    "Tumko Dekha To Yeh Khayal Aaya",
    "Chalte Chalte Mere Ye",
    "Bahon Mei Chali Aao",
    "Ek Do Teen",
    "Haaye Haaye Yeh Majboori",
    "Ye Chand Sa Roshan Chehra",
    "Munni Badnaam Hui",
    "Mai Shayar To Nai",
    "Haal Kaisa Hai Janaab Ka",
    "Ek Din Bik Jaayega Maati Ke Mol",
    "Bekaraar Krke Hume Yuu Naa",
    "Piyaa Tu Ab To Aajaa",
    "Hum To Tere Aashiq Hai",
    "Husn Haajir Hai Mohabbat Ke",
    "Husn Ke Laakhon Rang",
    "Hum Bewafa Hargiz Na The",
    "Aaja Aaja Mai Hu Pyaar Tera",
    "Chandi Jaisa Rang Hai Tera",
    "Koi Kahe Kehta Rahe",
    "Ye Kaali Kaali Aankhen",
    "Jai Jai Shiv Shankar",
    "Mere Angane Mei",
    "Jaane Kyu Log Mohabbat Kiyo",
    "Le Chal Le Chal Jeevan Saathi",
    "Dekha Na Haaye Re Socha Na",
    "Ghum Hai Kisi Ke Pyaar Mei",
    "Hai Apna Dil To Awaara",
    "Dil Kya Kare Jab Kisiko",
    "Bachna Aye Hasino",
    "Salam Ae Ishq Meri Jaan",
    "Leke Pehla Pehla Pyaar",
    "Hum Kaale Hai To Kya Hua",
    "Ke Pag Ghumguroo",
    "Ek Mai Aur Ek Tu",
    "Kaanta Laga Haaye Laga",
    "Kuch To Log Kahenge",
    "Chingaari Koi"
  ]